# Generated by Django 3.1 on 2020-09-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200902_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brief',
            field=models.CharField(default='brief', max_length=50, verbose_name='brief'),
            preserve_default=False,
        ),
    ]
