# Generated by Django 3.1 on 2020-09-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(default='url', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='heroku',
            field=models.URLField(default='heroku', max_length=50),
            preserve_default=False,
        ),
    ]
