# Generated by Django 3.1 on 2020-09-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200907_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='heroku',
            field=models.URLField(blank=True, max_length=50),
        ),
    ]
